version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    container_name: heybox-frontend
    environment:
      - NODE_ENV=production
